# Generated by Django 4.2.13 on 2024-05-30 10:28

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Login_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
