# Generated by Django 4.2.13 on 2024-05-30 11:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Login_App', '0002_alter_courses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
